project:
  type: website
  output-dir: docs

website:
  title: "Brian King"
  google-analytics: "G-G6MB3WX829"
  cookie-consent: true
  navbar:
    right:
      - text: "About"
        file: about.qmd
      - icon: github
        href: https://github.com/bking124
      - icon: twitter
        href: https://twitter.com/brian_el_rey
      - icon: linkedin
        href: https://www.linkedin.com/in/brianking387/
  
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css